// lib/constants.ts

export const SECTORS = {
  FINANCE: ['HDFCBANK.NS', 'ICICIBANK.NS', 'SBIN.NS', 'AXISBANK.NS', 'BAJFINANCE.NS'],
  IT: ['TCS.NS', 'INFY.NS', 'HCLTECH.NS', 'TECHM.NS', 'WIPRO.NS'],
  ENERGY: ['RELIANCE.NS', 'ONGC.NS', 'POWERGRID.NS', 'NTPC.NS'],
  AUTO: ['TATAMOTORS.NS', 'M&M.NS', 'MARUTI.NS', 'EICHERMOT.NS'],
  CONSUMER: ['ITC.NS', 'HINDUNILVR.NS', 'TITAN.NS', 'NESTLEIND.NS'],
  METALS: ['TATASTEEL.NS', 'HINDALCO.NS', 'JSWSTEEL.NS'],
};

export const INDICES = {
  NIFTY50: '^NSEI',
  BANKNIFTY: '^NSEBANK'
};